{{- if .Values.backends.websockets.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "deployment.fullname" . }}-websockets-proxy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "deployment.labels" . | indent 6 }}
spec:
  type: ClusterIP
  ports:
    - port: 9943
      name: {{ .Values.global.endpoints.networkShortName }}-ws
      targetPort: 9943
  selector:
    app: {{ template "deployment.name" . }}
    release: "{{ .Release.Name }}"
    component: {{ .Values.global.endpoints.networkName }}-websockets-proxy
{{- end }}