{{- if .Values.backends.healthCheck.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "deployment.fullname" . }}-health
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "deployment.labels" . | indent 6 }}
  annotations:
    {{- range $key, $value := .Values.backends.healthCheck.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.global.ssl.enabled }}
  tls:
    - hosts:
        {{- if .Values.global.endpoints.deployment.enabled }}
        - "{{ .Values.global.endpoints.deployment.domain }}"
        {{- end }}
        {{- if .Values.global.endpoints.aggregate.enabled }}
        - "{{ .Values.global.endpoints.aggregate.domain }}"
        {{- end }}
      secretName: {{ template "deployment.fullname" . }}-tls
  {{- end }}
  rules:
    {{- if .Values.global.endpoints.deployment.enabled }}
    - host: "{{ .Values.global.endpoints.deployment.domain }}"
      http:
        paths:
        - path: "/health"
          pathType: Prefix
          backend:
            service:
              name: {{ template "deployment.fullname" . }}-health
              port:
                number: {{ .Values.backends.healthCheck.upstreamServer.port }}
    {{- end }}
    {{- if .Values.global.endpoints.aggregate.enabled }}
    - host: "{{ .Values.global.endpoints.aggregate.domain }}"
      http:
        paths:
          - path: "/health"
            pathType: Prefix
            backend:
              service:
                name: {{ template "deployment.fullname" . }}-health
                port:
                  number: {{ .Values.backends.healthCheck.upstreamServer.port }}
    {{- end }}
{{- end }}