{{- if .Values.backends.jsonRPC.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "deployment.fullname" . }}-rpc-proxy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "deployment.labels" . | indent 6 }}
spec:
  type: ExternalName
  externalName: "{{ .Values.backends.jsonRPC.upstreamServer.uri }}"
{{- end }}