{{- if .Values.backends.jsonRPC.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "deployment.fullname" . }}-rpc-proxy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "deployment.labels" . | indent 6 }}
  annotations:
    {{- range $key, $value := .Values.backends.jsonRPC.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.global.ssl.enabled }}
  tls:
    - hosts:
        {{- if .Values.global.endpoints.deployment.enabled }}
        - "{{ .Values.global.endpoints.deployment.domain }}"
      secretName: {{ template "deployment.fullname" . }}-dep-tls
        {{- end }}
        {{- if .Values.global.endpoints.aggregate.enabled }}
        - "{{ .Values.global.endpoints.aggregate.domain }}"
      secretName: {{ template "deployment.fullname" . }}-agg-tls
  {{- end }}
  {{- end }}
  rules:
    {{- if .Values.global.endpoints.deployment.enabled }}
    - host: "{{ .Values.global.endpoints.deployment.domain }}"
      http:
        paths:
          - path: "/v0"
            pathType: Prefix
            backend:
              service:
                name: {{ template "deployment.fullname" . }}-rpc-proxy
                port:
                  number: {{ .Values.backends.jsonRPC.upstreamServer.port }}
    {{- end }}
    {{- if .Values.global.endpoints.aggregate.enabled }}
    - host: "{{ .Values.global.endpoints.aggregate.domain }}"
      http:
        paths:
          - path: "/v0"
            pathType: Prefix
            backend:
              service:
                name: {{ template "deployment.fullname" . }}-rpc-proxy
                port:
                  number: {{ .Values.backends.jsonRPC.upstreamServer.port }}
  {{- end }}
{{- end }}